In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
df = pd.read_csv(r'D:/570-AI/abalone.csv')

In [4]:
df

Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
0      M   0.455     0.365   0.095        0.5140          0.2245   
1      M   0.350     0.265   0.090        0.2255          0.0995   
2      F   0.530     0.420   0.135        0.6770          0.2565   
3      M   0.440     0.365   0.125        0.5160          0.2155   
4      I   0.330     0.255   0.080        0.2050          0.0895   
5      I   0.425     0.300   0.095        0.3515          0.1410   
6      F   0.530     0.415   0.150        0.7775          0.2370   
7      F   0.545     0.425   0.125        0.7680          0.2940   
8      M   0.475     0.370   0.125        0.5095          0.2165   
9      F   0.550     0.440   0.150        0.8945          0.3145   
10     F   0.525     0.380   0.140        0.6065          0.1940   
11     M   0.430     0.350   0.110        0.4060          0.1675   
12     M   0.490     0.380   0.135        0.5415          0.2175   
13     F   0.535     0.405   0.145        0.6845          0.2725   
14     F   0.470     0.355   0.100        0.4755          0.1675   
15     M   0.500     0.400   0.130        0.6645          0.2580   
16     I   0.355     0.280   0.085        0.2905          0.0950   
17     F   0.440     0.340   0.100        0.4510          0.1880   
18     M   0.365     0.295   0.080        0.2555          0.0970   
19     M   0.450     0.320   0.100        0.3810          0.1705   
20     M   0.355     0.280   0.095        0.2455          0.0955   
21     I   0.380     0.275   0.100        0.2255          0.0800   
22     F   0.565     0.440   0.155        0.9395          0.4275   
23     F   0.550     0.415   0.135        0.7635          0.3180   
24     F   0.615     0.480   0.165        1.1615          0.5130   
25     F   0.560     0.440   0.140        0.9285          0.3825   
26     F   0.580     0.450   0.185        0.9955          0.3945   
27     M   0.590     0.445   0.140        0.9310          0.3560   
28     M   0.605     0.475   0.180        0.9365          0.3940   
29     M   0.575     0.425   0.140        0.8635          0.3930   
...   ..     ...       ...     ...           ...             ...   
4147   M   0.695     0.550   0.195        1.6645          0.7270   
4148   M   0.770     0.605   0.175        2.0505          0.8005   
4149   I   0.280     0.215   0.070        0.1240          0.0630   
4150   I   0.330     0.230   0.080        0.1400          0.0565   
4151   I   0.350     0.250   0.075        0.1695          0.0835   
4152   I   0.370     0.280   0.090        0.2180          0.0995   
4153   I   0.430     0.315   0.115        0.3840          0.1885   
4154   I   0.435     0.330   0.095        0.3930          0.2190   
4155   I   0.440     0.350   0.110        0.3805          0.1575   
4156   M   0.475     0.370   0.110        0.4895          0.2185   
4157   M   0.475     0.360   0.140        0.5135          0.2410   
4158   I   0.480     0.355   0.110        0.4495          0.2010   
4159   F   0.560     0.440   0.135        0.8025          0.3500   
4160   F   0.585     0.475   0.165        1.0530          0.4580   
4161   F   0.585     0.455   0.170        0.9945          0.4255   
4162   M   0.385     0.255   0.100        0.3175          0.1370   
4163   I   0.390     0.310   0.085        0.3440          0.1810   
4164   I   0.390     0.290   0.100        0.2845          0.1255   
4165   I   0.405     0.300   0.085        0.3035          0.1500   
4166   I   0.475     0.365   0.115        0.4990          0.2320   
4167   M   0.500     0.380   0.125        0.5770          0.2690   
4168   F   0.515     0.400   0.125        0.6150          0.2865   
4169   M   0.520     0.385   0.165        0.7910          0.3750   
4170   M   0.550     0.430   0.130        0.8395          0.3155   
4171   M   0.560     0.430   0.155        0.8675          0.4000   
4172   F   0.565     0.450   0.165        0.8870          0.3700   
4173   M   0.590     0.440   0.135        0.9660          0.4

In [5]:
df['age'] = df['Rings']+1.5
df = df.drop('Rings', axis = 1)

In [6]:
df

Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
0      M   0.455     0.365   0.095        0.5140          0.2245   
1      M   0.350     0.265   0.090        0.2255          0.0995   
2      F   0.530     0.420   0.135        0.6770          0.2565   
3      M   0.440     0.365   0.125        0.5160          0.2155   
4      I   0.330     0.255   0.080        0.2050          0.0895   
5      I   0.425     0.300   0.095        0.3515          0.1410   
6      F   0.530     0.415   0.150        0.7775          0.2370   
7      F   0.545     0.425   0.125        0.7680          0.2940   
8      M   0.475     0.370   0.125        0.5095          0.2165   
9      F   0.550     0.440   0.150        0.8945          0.3145   
10     F   0.525     0.380   0.140        0.6065          0.1940   
11     M   0.430     0.350   0.110        0.4060          0.1675   
12     M   0.490     0.380   0.135        0.5415          0.2175   
13     F   0.535     0.405   0.145        0.6845          0.2725   
14     F   0.470     0.355   0.100        0.4755          0.1675   
15     M   0.500     0.400   0.130        0.6645          0.2580   
16     I   0.355     0.280   0.085        0.2905          0.0950   
17     F   0.440     0.340   0.100        0.4510          0.1880   
18     M   0.365     0.295   0.080        0.2555          0.0970   
19     M   0.450     0.320   0.100        0.3810          0.1705   
20     M   0.355     0.280   0.095        0.2455          0.0955   
21     I   0.380     0.275   0.100        0.2255          0.0800   
22     F   0.565     0.440   0.155        0.9395          0.4275   
23     F   0.550     0.415   0.135        0.7635          0.3180   
24     F   0.615     0.480   0.165        1.1615          0.5130   
25     F   0.560     0.440   0.140        0.9285          0.3825   
26     F   0.580     0.450   0.185        0.9955          0.3945   
27     M   0.590     0.445   0.140        0.9310          0.3560   
28     M   0.605     0.475   0.180        0.9365          0.3940   
29     M   0.575     0.425   0.140        0.8635          0.3930   
...   ..     ...       ...     ...           ...             ...   
4147   M   0.695     0.550   0.195        1.6645          0.7270   
4148   M   0.770     0.605   0.175        2.0505          0.8005   
4149   I   0.280     0.215   0.070        0.1240          0.0630   
4150   I   0.330     0.230   0.080        0.1400          0.0565   
4151   I   0.350     0.250   0.075        0.1695          0.0835   
4152   I   0.370     0.280   0.090        0.2180          0.0995   
4153   I   0.430     0.315   0.115        0.3840          0.1885   
4154   I   0.435     0.330   0.095        0.3930          0.2190   
4155   I   0.440     0.350   0.110        0.3805          0.1575   
4156   M   0.475     0.370   0.110        0.4895          0.2185   
4157   M   0.475     0.360   0.140        0.5135          0.2410   
4158   I   0.480     0.355   0.110        0.4495          0.2010   
4159   F   0.560     0.440   0.135        0.8025          0.3500   
4160   F   0.585     0.475   0.165        1.0530          0.4580   
4161   F   0.585     0.455   0.170        0.9945          0.4255   
4162   M   0.385     0.255   0.100        0.3175          0.1370   
4163   I   0.390     0.310   0.085        0.3440          0.1810   
4164   I   0.390     0.290   0.100        0.2845          0.1255   
4165   I   0.405     0.300   0.085        0.3035          0.1500   
4166   I   0.475     0.365   0.115        0.4990          0.2320   
4167   M   0.500     0.380   0.125        0.5770          0.2690   
4168   F   0.515     0.400   0.125        0.6150          0.2865   
4169   M   0.520     0.385   0.165        0.7910          0.3750   
4170   M   0.550     0.430   0.130        0.8395          0.3155   
4171   M   0.560     0.430   0.155        0.8675          0.4000   
4172   F   0.565     0.450   0.165        0.8870          0.3700   
4173   M   0.590     0.440   0.135        0.9660          0.4

In [7]:
x = df.iloc[:, 0:8].values
y = df.iloc[:, 8].values

In [8]:
x

array([['M', 0.455, 0.365, ..., 0.2245, 0.10099999999999999, 0.15],
       ['M', 0.35, 0.265, ..., 0.0995, 0.0485, 0.07],
       ['F', 0.53, 0.42, ..., 0.2565, 0.1415, 0.21],
       ...,
       ['M', 0.6, 0.475, ..., 0.5255, 0.2875, 0.308],
       ['F', 0.625, 0.485, ..., 0.531, 0.261, 0.29600000000000004],
       ['M', 0.71, 0.555, ..., 0.9455, 0.3765, 0.495]], dtype=object)

In [9]:
y

array([16.5,  8.5, 10.5, ..., 10.5, 11.5, 13.5])

In [10]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [11]:
x[:,0]=le.fit_transform(x[:,0])

In [12]:
x

array([[2, 0.455, 0.365, ..., 0.2245, 0.10099999999999999, 0.15],
       [2, 0.35, 0.265, ..., 0.0995, 0.0485, 0.07],
       [0, 0.53, 0.42, ..., 0.2565, 0.1415, 0.21],
       ...,
       [2, 0.6, 0.475, ..., 0.5255, 0.2875, 0.308],
       [0, 0.625, 0.485, ..., 0.531, 0.261, 0.29600000000000004],
       [2, 0.71, 0.555, ..., 0.9455, 0.3765, 0.495]], dtype=object)

In [13]:
from sklearn.preprocessing import OneHotEncoder
oh=OneHotEncoder(categorical_features=[0])

In [14]:
x=oh.fit_transform(x).toarray()

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [15]:
x

array([[0.    , 0.    , 1.    , ..., 0.2245, 0.101 , 0.15  ],
       [0.    , 0.    , 1.    , ..., 0.0995, 0.0485, 0.07  ],
       [1.    , 0.    , 0.    , ..., 0.2565, 0.1415, 0.21  ],
       ...,
       [0.    , 0.    , 1.    , ..., 0.5255, 0.2875, 0.308 ],
       [1.    , 0.    , 0.    , ..., 0.531 , 0.261 , 0.296 ],
       [0.    , 0.    , 1.    , ..., 0.9455, 0.3765, 0.495 ]])

In [16]:
x=x[:,1:10]

In [17]:
x

array([[0.    , 1.    , 0.455 , ..., 0.2245, 0.101 , 0.15  ],
       [0.    , 1.    , 0.35  , ..., 0.0995, 0.0485, 0.07  ],
       [0.    , 0.    , 0.53  , ..., 0.2565, 0.1415, 0.21  ],
       ...,
       [0.    , 1.    , 0.6   , ..., 0.5255, 0.2875, 0.308 ],
       [0.    , 0.    , 0.625 , ..., 0.531 , 0.261 , 0.296 ],
       [0.    , 1.    , 0.71  , ..., 0.9455, 0.3765, 0.495 ]])

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [19]:
x_train

array([[0.    , 1.    , 0.48  , ..., 0.2925, 0.1405, 0.1575],
       [1.    , 0.    , 0.32  , ..., 0.0615, 0.0275, 0.0355],
       [0.    , 1.    , 0.525 , ..., 0.428 , 0.1415, 0.2045],
       ...,
       [0.    , 1.    , 0.52  , ..., 0.2565, 0.1265, 0.17  ],
       [0.    , 1.    , 0.51  , ..., 0.27  , 0.1665, 0.205 ],
       [1.    , 0.    , 0.365 , ..., 0.0915, 0.0475, 0.063 ]])

In [20]:
x_test

array([[0.    , 0.    , 0.415 , ..., 0.1595, 0.0785, 0.12  ],
       [0.    , 0.    , 0.62  , ..., 0.477 , 0.236 , 0.275 ],
       [0.    , 1.    , 0.45  , ..., 0.18  , 0.1185, 0.155 ],
       ...,
       [0.    , 1.    , 0.365 , ..., 0.0855, 0.0515, 0.07  ],
       [1.    , 0.    , 0.53  , ..., 0.2025, 0.101 , 0.148 ],
       [0.    , 0.    , 0.585 , ..., 0.381 , 0.1615, 0.315 ]])

In [21]:
y_train

array([ 7.5,  8.5, 10.5, ..., 11.5, 13.5,  7.5])

In [22]:
y_test

array([13.5,  9.5, 11.5, 13.5, 13.5, 10.5,  9.5, 17.5, 21.5,  7.5, 11.5,
       10.5, 12.5, 10.5, 10.5, 11.5, 13.5, 10.5, 10.5, 11.5,  8.5, 14.5,
       10.5,  9.5, 10.5, 15.5,  8.5,  7.5, 12.5,  8.5,  8.5, 10.5,  8.5,
       11.5, 15.5,  8.5, 11.5, 11.5, 11.5,  8.5, 14.5, 11.5, 11.5, 12.5,
        6.5, 10.5,  9.5, 10.5,  8.5,  8.5, 15.5, 10.5, 13.5, 10.5,  7.5,
       14.5, 13.5,  8.5, 10.5, 10.5, 11.5,  9.5, 13.5,  7.5, 11.5,  8.5,
       15.5, 15.5,  9.5, 11.5, 10.5,  9.5, 12.5,  9.5,  9.5,  8.5, 12.5,
       12.5,  7.5, 11.5, 11.5, 10.5, 10.5, 10.5,  9.5, 14.5,  9.5, 10.5,
       10.5, 12.5,  8.5,  9.5,  4.5,  9.5, 11.5, 13.5, 11.5, 15.5, 11.5,
       10.5, 10.5, 10.5, 10.5, 11.5,  8.5, 10.5, 14.5,  8.5,  8.5,  9.5,
       13.5, 10.5,  9.5,  9.5, 12.5,  8.5, 12.5, 10.5, 15.5,  9.5, 11.5,
        8.5, 10.5,  8.5,  9.5, 11.5, 12.5,  7.5, 11.5,  9.5,  7.5, 12.5,
       10.5, 11.5, 10.5, 14.5,  9.5, 12.5,  7.5, 15.5, 10.5, 20.5,  7.5,
       11.5,  8.5, 10.5, 13.5, 12.5, 11.5, 11.5, 10

In [23]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)



In [24]:
 from sklearn.linear_model import LinearRegression

In [25]:
mlr=LinearRegression()

In [26]:
mlr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [27]:
y_pred=mlr.predict(x_test)

In [28]:
x_test

array([[-0.70583843, -0.75397633, -0.92931108, ..., -0.89731521,
        -0.94478804, -0.87060025],
       [-0.70583843, -0.75397633,  0.77269622, ...,  0.48348186,
         0.45453189,  0.2253785 ],
       [-0.70583843,  1.32630159, -0.63872447, ..., -0.80816139,
        -0.5894052 , -0.62312118],
       ...,
       [-0.70583843,  1.32630159, -1.34443481, ..., -1.21913878,
        -1.18467145, -1.22414178],
       [ 1.41675483, -0.75397633,  0.0254735 , ..., -0.71030963,
        -0.74488519, -0.67261699],
       [-0.70583843, -0.75397633,  0.48210961, ...,  0.06598101,
        -0.20736865,  0.50821172]])

In [29]:
y_pred

array([10.30643318, 11.24804848, 11.06664543, 13.01425108, 12.1856026 ,
       11.41777854, 11.0338684 , 15.13338009, 15.43910229,  9.08016146,
       11.89223912, 11.43046882, 10.30056986, 12.26682042, 13.09583578,
       12.37597632, 10.19095078, 13.17304927, 10.19954782, 12.20057687,
       10.56339   , 15.28264544, 11.98527223,  7.79745364, 11.58875481,
       13.03048601,  8.95777764,  8.39024965, 11.95817625,  9.07108386,
       12.62590837,  9.10703684,  8.30656182, 12.97731224, 12.21703542,
        8.7313339 , 11.51894306, 10.8756662 , 10.5642726 ,  9.69890609,
       14.10030916, 10.58485948, 10.77052753, 13.21804102,  6.57786971,
       12.62363964, 10.55808711, 11.92045339,  8.78197743, 10.38886884,
       12.72144959, 10.43537418, 16.1325791 , 11.4568262 ,  8.50373016,
       13.88793302, 12.95098571,  9.03044423,  9.31937508,  7.39723456,
        9.95939777, 10.82549138, 15.52960909,  7.75498622, 11.46417791,
        8.18264369, 14.1473741 , 14.86485688, 11.43428642, 12.48

In [30]:
y_test

array([13.5,  9.5, 11.5, 13.5, 13.5, 10.5,  9.5, 17.5, 21.5,  7.5, 11.5,
       10.5, 12.5, 10.5, 10.5, 11.5, 13.5, 10.5, 10.5, 11.5,  8.5, 14.5,
       10.5,  9.5, 10.5, 15.5,  8.5,  7.5, 12.5,  8.5,  8.5, 10.5,  8.5,
       11.5, 15.5,  8.5, 11.5, 11.5, 11.5,  8.5, 14.5, 11.5, 11.5, 12.5,
        6.5, 10.5,  9.5, 10.5,  8.5,  8.5, 15.5, 10.5, 13.5, 10.5,  7.5,
       14.5, 13.5,  8.5, 10.5, 10.5, 11.5,  9.5, 13.5,  7.5, 11.5,  8.5,
       15.5, 15.5,  9.5, 11.5, 10.5,  9.5, 12.5,  9.5,  9.5,  8.5, 12.5,
       12.5,  7.5, 11.5, 11.5, 10.5, 10.5, 10.5,  9.5, 14.5,  9.5, 10.5,
       10.5, 12.5,  8.5,  9.5,  4.5,  9.5, 11.5, 13.5, 11.5, 15.5, 11.5,
       10.5, 10.5, 10.5, 10.5, 11.5,  8.5, 10.5, 14.5,  8.5,  8.5,  9.5,
       13.5, 10.5,  9.5,  9.5, 12.5,  8.5, 12.5, 10.5, 15.5,  9.5, 11.5,
        8.5, 10.5,  8.5,  9.5, 11.5, 12.5,  7.5, 11.5,  9.5,  7.5, 12.5,
       10.5, 11.5, 10.5, 14.5,  9.5, 12.5,  7.5, 15.5, 10.5, 20.5,  7.5,
       11.5,  8.5, 10.5, 13.5, 12.5, 11.5, 11.5, 10

In [31]:
mlr.intercept_

11.443430110745314

In [32]:
x_train.shape

(3341, 9)

In [33]:
pre=mlr.predict([[0,1,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500]])

In [34]:
pre

array([13.37076246])

In [35]:
from sklearn.metrics import r2_score

In [36]:
r2_score(y_test,y_pred)

0.4898742452607189

In [37]:
df.corr()

Length  Diameter    Height  Whole weight  Shucked weight  \
Length          1.000000  0.986812  0.827554      0.925261        0.897914   
Diameter        0.986812  1.000000  0.833684      0.925452        0.893162   
Height          0.827554  0.833684  1.000000      0.819221        0.774972   
Whole weight    0.925261  0.925452  0.819221      1.000000        0.969405   
Shucked weight  0.897914  0.893162  0.774972      0.969405        1.000000   
Viscera weight  0.903018  0.899724  0.798319      0.966375        0.931961   
Shell weight    0.897706  0.905330  0.817338      0.955355        0.882617   
age             0.556720  0.574660  0.557467      0.540390        0.420884   

                Viscera weight  Shell weight       age  
Length                0.903018      0.897706  0.556720  
Diameter              0.899724      0.905330  0.574660  
Height                0.798319      0.817338  0.557467  
Whole weight          0.966375      0.955355  0.540390  
Shucked weight        0.931961      0.882617  0.420884  
Viscera weight        1.000000      0.907656  0.503819  
Shell weight          0.907656      1.000000  0.627574  
age                   0.503819      0.627574  1.000000